### ISSUE TITLE
Not running on google colab!!!

### ISSUE THREAD

**Issue by smalekz** [Giffy/MongoDB_PyMongo_Tutorial#1]
localhost:27017: [Errno 111] Connection refused

**Comment by Giffy** [comment]
This error happens when it isn't possible to connect to MongoDB.
Code was released for a workshop and students executed this demo on Colab. Now fails because Google changed the way as colab works.
Now each notebook starts a new instance (like a new computer). 
Currently, it isn't possible to run MongoDB server in one notebook and access to the database from a different one.
You can run te code in your local computer, intalling and running MongoDB localy.

**Comment by Giffy** [comment]
Updated notebooks to run with "https://console.clever-cloud.com/".
I recommend to sing up and use your own server.
