### ISSUE TITLE
Running mongodb in the backend 

### ISSUE THREAD

**Issue by PExplorer** [Giffy/MongoDB_PyMongo_Tutorial#2]
Hi, 

I would like to run mongodb server in the backend in google colab. I started server in one cell of the notebook. I am not able to execute other cells as long as the cell with server start command is running. 
Please let me know if I can mongodb server in the backend. If yes, how can i do it?

Thank you, 
Pradeep

**Comment by Giffy** [comment]
Hi Pradeep,
Google changed the way the instances are created and it's not possible to run mongodb in background.
I recommend to locally mongodb and the tutorial notebooks.  Linux commands are in the notebook.

Another solution is to deploy a mongo database online, for example in  https://mlab.com/ ,
be aware that you could not execute many if database management commands due to mlab service policies. 

Regards,
J

**Comment by Giffy** [comment]
Updated notebooks to run with "https://console.clever-cloud.com/".
I recommend to sing up and use your own server.
